version: '2.1'
services:
  app:
    restart: always
    build: .
    ports:
      - 5000:5000
    volumes:
      - .:/app
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env
    expose:
      - 5432